// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CjqeNWc10xHWnt-9PDZ4tUk6q1ZFSng',
    appId: '1:102077048970:web:492c81062e9024b6dda573',
    messagingSenderId: '102077048970',
    projectId: 'laptrinhdidong-104339',
    authDomain: 'laptrinhdidong-104339.firebaseapp.com',
    storageBucket: 'laptrinhdidong-104339.firebasestorage.app',
    measurementId: 'G-VEG3Q0ZN7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegglIFZyZ4cgJaU6gct_CNY9F1ssdo08',
    appId: '1:102077048970:android:c835b1eb2b33ee12dda573',
    messagingSenderId: '102077048970',
    projectId: 'laptrinhdidong-104339',
    storageBucket: 'laptrinhdidong-104339.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbfWttkJrmQ0AP-o6dPAvlhC_gGOiTdzg',
    appId: '1:102077048970:ios:17f9fcabb98055e6dda573',
    messagingSenderId: '102077048970',
    projectId: 'laptrinhdidong-104339',
    storageBucket: 'laptrinhdidong-104339.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbfWttkJrmQ0AP-o6dPAvlhC_gGOiTdzg',
    appId: '1:102077048970:ios:17f9fcabb98055e6dda573',
    messagingSenderId: '102077048970',
    projectId: 'laptrinhdidong-104339',
    storageBucket: 'laptrinhdidong-104339.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5CjqeNWc10xHWnt-9PDZ4tUk6q1ZFSng',
    appId: '1:102077048970:web:999111dd39fb3676dda573',
    messagingSenderId: '102077048970',
    projectId: 'laptrinhdidong-104339',
    authDomain: 'laptrinhdidong-104339.firebaseapp.com',
    storageBucket: 'laptrinhdidong-104339.firebasestorage.app',
    measurementId: 'G-28JQW50T4X',
  );

}